---

# should be run with 'become: yes'

- name: Run apt-get update
  raw: apt-get update

- name: Install python-simplejson
  raw: apt-get install -y python-simplejson

- name: Reconfigure buggy ubuntu locales
  template: src=../files/locale dest=/etc/default/locale
    owner=root mode="u=rw,g=r,o=r" force=yes

- name: Upload ssh key file "{{ pub_key_file }}"
  authorized_key: user=ubuntu key="{{ lookup('file', '{{ pub_key_file }}') }}"
  when: upload_key

- name: Update apt cache
  apt: update_cache=yes

- name: Install misc packages
  apt: name={{ item }} state=present
  with_items:
    - htop
    - iotop
    - mc
    - gcc
    - git
    - software-properties-common
    - python-pip

- name: Update pip
  pip:
    name: pip
    state: latest

- name: Add swap file
  script: increase_swap.sh {{ swapsize }}
  when: swapsize|int > 0
