---

- name: Run apt-get update
  become: yes
  raw: apt-get update

- name: Install python-simplejson
  become: yes
  raw: apt-get install -y python-simplejson

- name: Reconfigure buggy ubuntu locales
  become: yes
  template: src=../files/locale dest=/etc/default/locale
    owner=root mode="u=rw,g=r,o=r" force=yes

- name: Create ubuntu user
  become: yes
  user:
    name: ubuntu
    shell: /bin/bash
    groups: sudo

- name: Upload ssh key file "{{ pub_key_file }}"
  become: yes
  authorized_key: user=ubuntu key="{{ lookup('file', '{{ pub_key_file }}') }}"
  when: upload_key

- name: Install misc packages
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - htop
    - iotop
    - mc
    - gcc
    - git
    - software-properties-common
    - python-pip
    - libssl-dev

- name: Update pip
  become: yes
  pip:
    name: pip
    state: latest

- name: Add a swap file if doesn't exist
  become: yes
  script: increase_swap.sh {{ swapsize }}
  when: swapsize|int > 0

- name: Set timezone
  become: yes
  timezone: name={{ time_zone_name }}
