---

- name: Install psycopg2 into the system Python site, so that Ansible modules can use it
  become: yes
  pip: name=psycopg2 state=present

- name: Create MolDB postgres user
  postgresql_user: name=mol_db password={{ mol_db_postgres_pass }} role_attr_flags=CREATEDB
  become: yes
  become_user: postgres

- name: Create MolDB postgres database
  become: yes
  become_user: postgres
  postgresql_db: name=mol_db owner=mol_db encoding=UTF8

- name: Clone MolDB git repository
  git: >
    dest={{ mol_db_home }}
    repo=https://github.com/METASPACE2020/sm-molecular-db.git
    update=yes
    version={{ mol_db_branch }}

- name: Check if env already exists
  args:
    chdir: "{{ mol_db_home }}"
    executable: /bin/bash
  shell: "conda env list"
  register: conda_envs

- name: Create conda environment (from environment.yml file) if it doesn't exist
  args:
    chdir: "{{ mol_db_home }}"
    executable: /bin/bash
  shell: "conda env create"
  when: not ('mol_db' in conda_envs.stdout)

- name: Update conda environment (from environment.yml file) if it exists
  args:
    chdir: "{{ mol_db_home }}"
    executable: /bin/bash
  shell: "conda env update -f environment.yml"
  when: ('mol_db' in conda_envs.stdout)

- name: Install OpenBabel
  apt: name=openbabel state=latest
  become: yes

- name: Install openbabel into conda environment
  args:
    chdir: "{{ mol_db_home }}"
    executable: /bin/bash
  shell: >
    source {{ mol_db_miniconda_prefix }}/bin/activate {{ mol_db_miniconda_env.name }}
    && conda install -c openbabel openbabel

- name: Pull MolDB config from the remote host
  fetch: src={{ mol_db_home }}/conf/local.ini.template dest=/tmp/local.ini.template
         flat=yes fail_on_missing=yes

- name: Put MolDB config to ./conf/local.ini
  template: src=/tmp/local.ini.template dest={{ mol_db_home }}/conf/local.ini
            owner=ubuntu group=ubuntu mode=0600

- name: Make sure that the logs directory exists
  file: path={{ mol_db_home }}/logs state=directory mode=0755

- name: Copy supervisor config file
  template: src=mol-db-api.supervisor.j2 dest=/etc/supervisor/sm-mol-db-api.supervisor
            mode=0600 owner=ubuntu group=ubuntu
