---

- name: Deploying SM web app code
  user: ubuntu
  hosts: web

  vars_files:
    - ../vars/web_app.yml

  tasks:
    - name: Clone sm-web-app git repository
      git:
        dest: "{{ sm_webapp_home }}"
        repo: https://github.com/METASPACE2020/sm-webapp.git
        update: yes
        force: yes
        recursive: yes
        version: "{{ sm_webapp_branch }}"
      register: git_deploy
      until: git_deploy | succeeded

    - name: Pull config template from the remote host
      fetch: src={{ sm_webapp_home }}/conf.js.template dest=/tmp/conf.js.template
             flat=yes fail_on_missing=yes

    - name: Save config as ./conf.js
      template: src=/tmp/conf.js.template dest={{ sm_webapp_home }}/conf.js
                owner=ubuntu group=ubuntu mode=0600

    - name: Pull client config template from the remote host
      fetch: src={{ sm_webapp_home }}/src/clientConfig.json.template dest=/tmp/clientConfig.json.template
             flat=yes fail_on_missing=yes

    - name: Save client config as ./src/clientConfig.json
      template: src=/tmp/clientConfig.json.template dest={{ sm_webapp_home }}/src/clientConfig.json
                owner=ubuntu group=ubuntu mode=0600

    - name: Install sm-web-app dependencies
      shell: npm install
      args:
        chdir: "{{ sm_webapp_home }}"
        executable: /bin/bash

    - name: Dereference metadata schema
      shell: node deref_schema.js > src/assets/metadata_schema.json
      args:
        chdir: "{{ sm_webapp_home }}"
        executable: /bin/bash

    - name: Run build app
      shell: npm run build
      args:
        chdir: "{{ sm_webapp_home }}"
        executable: /bin/bash

    - include: ../../restart_supervisor.yml supervisor_app=sm-web-app
