miniconda_systems:
  Linux: Linux
  Darwin: MacOSX
miniconda_architecture:
  x86_64: x86_64
  amd64: x86_64
  i386: x86
  armv7l: armv7l
  ppc64le: ppc64le

miniconda_installer: Miniconda{{ miniconda_python }}-{{ miniconda_version }}-{{ miniconda_systems[ansible_system] }}-{{ miniconda_architecture[ansible_architecture] }}.sh
