---

- name: Install Redis
  become: yes
  apt: name=redis-server state=latest

- name: Clean sm-web-app folder
  file: name={{ sm_webapp_home}} state=absent

- name: Clone sm-web-app git repository
  git:
    dest: "{{ sm_webapp_home }}"
    repo: https://github.com/METASPACE2020/sm-webapp.git
    update: yes
    force: yes
    recursive: yes
    version: "{{ sm_webapp_branch }}"

- name: Pull config template from the remote host
  fetch: src={{ sm_webapp_home }}/conf.js.template dest=/tmp/conf.js.template
         flat=yes fail_on_missing=yes

- name: Save config as ./conf.js
  template: src=/tmp/conf.js.template dest={{ sm_webapp_home }}/conf.js
            owner=ubuntu group=ubuntu mode=0600

- name: Pull client config template from the remote host
  fetch: src={{ sm_webapp_home }}/src/clientConfig.json.template dest=/tmp/clientConfig.json.template
         flat=yes fail_on_missing=yes

- name: Save client config as ./src/clientConfig.json
  template: src=/tmp/clientConfig.json.template dest={{ sm_webapp_home }}/src/clientConfig.json
            owner=ubuntu group=ubuntu mode=0600

- name: Make sure that the logs directory exists
  file: path={{ sm_webapp_home }}/logs state=directory mode=0755

- name: Create upload directory
  file: path={{ sm_webapp_upload_destination }} state=directory mode=0755
  when: sm_webapp_upload_destination != 's3'

- name: Copy supervisor config file
  template: src=sm-web-app.supervisor.j2 dest=/etc/supervisor/sm-web-app.supervisor
            mode=0600 owner=ubuntu group=ubuntu
