miniconda_python: 3
miniconda_version: latest
miniconda_installer_checksum: ""
miniconda_prefix: "{{ ansible_env.HOME }}/miniconda{{ miniconda_python if miniconda_python == 3 else '' }}"
miniconda_update_conda: False
miniconda_env: ""