---

- name: Clone sm-graphql git repository
  git:
    dest: "{{ sm_graphql_home }}"
    repo: https://github.com/METASPACE2020/sm-graphql.git
    update: yes
    force: yes
    recursive: yes
    track_submodules: no  # submodules refer to commit specified in the main repository
    version: "{{ sm_graphql_branch }}"

- name: Install sm-graphql dependencies
  shell: npm install
  args:
    chdir: "{{ sm_graphql_home }}"
    executable: /bin/bash

- name: Pull config from the remote host
  fetch: src={{ sm_graphql_home }}/config/config.js.template dest=/tmp/config.js.template
         flat=yes fail_on_missing=yes

- name: Save config as ./config/production.js
  template: src=/tmp/config.js.template dest={{ sm_graphql_home }}/config/production.js
            owner=ubuntu group=ubuntu mode=0600

- name: Create folders for images
  file:
    path: /opt/data/sm_data/public/{{ item }}
    state: directory
    mode: 0755
  with_items:
     - optical_images
     - raw_optical_images
     - iso_images

- name: Make sure that the logs directory exists
  file: path={{ sm_graphql_home }}/logs state=directory mode=0755

- name: Copy supervisor config file
  template: src=sm-graphql.supervisor.j2 dest=/etc/supervisor/sm-graphql.supervisor
            mode=0600 owner=ubuntu group=ubuntu
