- name: Clone sm-graphql git repository
  git:
    dest: "{{ sm_graphql_home }}"
    repo: https://github.com/METASPACE2020/sm-graphql.git
    update: yes
    force: yes
    recursive: yes
    track_submodules: no  # submodules refer to commit specified in the web app repository
    version: "{{ sm_graphql_branch }}"
  when: local_deploy is not defined
  register: git_deploy
  until: git_deploy | succeeded

- name: Upload local files
  synchronize:
    src: "{{ sm_graphql_home }}/"
    dest: "{{ sm_graphql_home }}/"
    rsync_opts:
      - "--exclude='config/*.js' --exclude='logs/*' --exclude='dist/*' --exclude='node_modules/*' --exclude='.*'"
  when: local_deploy is defined

- name: Install sm-graphql dependencies
  shell: yarn install
  args:
    chdir: "{{ sm_graphql_home }}"
    executable: /bin/bash

- name: Dereference metadata schema
  shell: node deref_schema.js > metadata_schema.json
  args:
    chdir: "{{ sm_graphql_home }}"
    executable: /bin/bash

- name: Pull config from the remote host
  fetch: src={{ sm_graphql_home }}/config/config.js.template dest=/tmp/config.js.template
         flat=yes fail_on_missing=yes

- name: Save config as ./config/production.js
  template: src=/tmp/config.js.template dest={{ sm_graphql_home }}/config/production.js
            owner=ubuntu group=ubuntu mode=0600

- import_tasks: ../restart_supervisor.yml supervisor_app=sm-graphql
