
- name: Check if supervisord daemon is running
  shell: supervisorctl status
  args:
    executable: /bin/bash
  register: supervisorctl_status_out


- name: Start supervisord daemon
  shell: >
    supervisord -c /etc/supervisor/supervisord.conf -l /var/log/supervisor/supervisord.log
    && supervisorctl stop all
  args:
    executable: /bin/bash
  register: command_result
  when: "'no such file' in supervisorctl_status_out.stdout"

#- debug: var=command_result
#  when: "'no such file' in supervisorctl_status_out.stdout"
#  failed_when: '"ERROR" in command_result.stdout or "FATAL" in command_result.stdout'


- name: "Restart {{ supervisor_app | default('all') }} app(s) running under supervisor"
  shell: >
    supervisorctl reread
    && supervisorctl update
    && supervisorctl restart {{ supervisor_app | default("all") }}
  args:
    executable: /bin/bash

- name: Check {{ supervisor_app | default('all') }} app(s) status
  shell: supervisorctl status {{ supervisor_app | default("all") }}
  args:
    executable: /bin/bash
  register: command_result

- debug: var=command_result
  failed_when: >
    ('"ERROR" in command_result.stdout or "FATAL" in command_result.stdout' or "BACKOFF" in command_result.stdout)
