name: sm_distributed
channels:
  - salford_systems
dependencies:
  - python=2.7
  - pip
  - numpy=1.10
  - scipy=0.17.0
  - numba=0.24.0
  - pandas=0.18.0
  - matplotlib-nogui
  - mock=1.3.0
  - Fabric=1.10.2
  - pytest
  - lxml
  - psycopg2=2.6.1
  - cffi
  - pip:
    - pyMSpec==0.1
    - pyImagingMSpec==0.1.1
    - cpyMSpec==0.1.1
    - cpyImagingMSpec==0.0.4
    - py4j==0.9
    - tornado==4.2.1
    - pypng
    - pyimzML==1.0.1
    - tornpsql==1.1.0
    - requests
    - recommonmark
    - boto3==1.3.0