name: sm_engine
channels:
  - salford_systems
dependencies:
  - python=2.7
  - pip
  - numpy=1.10
  - scipy=0.17.0
  - numba=0.24.0
  - pandas=0.18.0
  - matplotlib-nogui
  - mock=1.3.0
  - Fabric=1.10.2
  - pytest
  - lxml
  - libgcc
  - psycopg2=2.6.1
  - cffi
  - pip:
    - pyMSpec
    - pyImagingMSpec
    - cpyMSpec
    - cpyImagingMSpec
    - py4j==0.9
    - tornado==4.2.1
    - tornpsql==1.1.0
    - pyimzML==1.0.1
    - requests
    - recommonmark
    - boto3==1.3.0
    - networkx
    - supervisor
    - pyyaml
    - elasticsearch
